name: voip
envs:
  - key: APIKEY
    scope: RUN_AND_BUILD_TIME
    value: "JWAPZTCWXLCHAYZNWWRGCQNZASGHRIXFXQSWUZZXNGNYBMPDOKRBEHLKFKOWCWUZTFAVWCTZFSJNHJUNWJSKGUQUHUFR"
  - key: SITEURL
    scope: RUN_AND_BUILD_TIME
    value: "https://example.com"
  - key: PORT
    scope: RUN_AND_BUILD_TIME
    value: "7777"
services:
  - name: web
    github:
      repo: eper-io/voip
      branch: main