name: voip
envs:
  - key: APIKEY
    scope: RUN_AND_BUILD_TIME
    value: "SEBIEJTAEFRNWFSJBLJVTREQICBZVLORWZVLJHKSYTCJZZPATQSSHABBKEAGULFRLTVJQTRZRIRLHAMEUOWKROQZIINR"
  - key: SITEURL
    scope: RUN_AND_BUILD_TIME
    value: "https://l.eper.io"
services:
  - name: web
    github:
      repo: eper-io/voip
      branch: main