#!/bin/sh

echo "Hello World.  The time is now $(date -R)!" | tee /root/output.txt

yum install -y golang

cat <<EOF >/tmp/main.go
package main

import (
    "fmt"
    "net/http"
)

func handler(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Hello, World!")
}

func main() {
    http.HandleFunc("/", handler)
    port := ":7777"

    err := http.ListenAndServe(port, nil)
    if err != nil {
        fmt.Println(err)
    }
}
EOF

go run /tmp/main.go
