#!/bin/bash

# The output can be grabbed at /var/log/cloud-init-output.log

sudo echo "Hello World.  The time is now $(date -R)!" | tee /var/log/output.txt

systemctl disable firewalld
systemctl stop firewalld
sudo yum install -y golang

sudo cat <<EOF >/tmp/main.go
package main

import (
    "fmt"
    "net/http"
)

func handler(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Hello, World!")
}

func main() {
    http.HandleFunc("/", handler)
    port := ":80"

    err := http.ListenAndServe(port, nil)
    if err != nil {
        fmt.Println(err)
    }
}
EOF

sudo nohup go run /tmp/main.go &
